spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/file-upload # mudar para loja_popular
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.security: INFO

security:
  jwt:
    issuer: lojas-popular-moveis
    access-token:
      ttl-seconds: 3600
    refresh-token:
      ttl-seconds: 604800
    # TROCAR EM PRODUCAO (>=64 bytes):
    secret: "change-me-in-prod-64-bytes-minimum-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"

cors:
  allowed-origins:
    - "http://localhost:5173"
    - "http://localhost:3000"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"

mercadopago:
  access-token: "TEST-1375941359691268-102215-39248d21f780d675f5368f4d4035c269-184393666"
  base-url: "https://api.mercadopago.com"
  # opcional: segredo para validar assinatura do webhook (se configurado no MP)
  webhook:
    secret: "TEST-1375941359691268-102215-39248d21f780d675f5368f4d4035c269-184393666"
