--
-- Baseline schema (Lojas Popular Backend), gerado a partir das entidades JPA
-- via Hibernate ddl-auto=create + pg_dump --schema-only.
--

--
-- Name: auditoria_evento; Type: TABLE; Schema: public
--

CREATE TABLE public.auditoria_evento (
    data_evento timestamp(6) with time zone,
    id bigint NOT NULL,
    usuario_id bigint,
    descricao character varying(255),
    tipo character varying(255),
    CONSTRAINT auditoria_evento_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['LOGIN_SUCESSO'::character varying, 'LOGIN_FALHA'::character varying, 'PEDIDO_CRIADO'::character varying, 'PAGAMENTO_APROVADO'::character varying, 'PAGAMENTO_REJEITADO'::character varying, 'PRODUTO_CRIADO'::character varying, 'PRODUTO_ATUALIZADO'::character varying, 'PRODUTO_REMOVIDO'::character varying, 'NOTIFICACAO_FALHA'::character varying, 'NOTIFICACAO_ENVIADA'::character varying])::text[])))
);

ALTER TABLE public.auditoria_evento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auditoria_evento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: categorias; Type: TABLE; Schema: public
--

CREATE TABLE public.categorias (
    ativa boolean NOT NULL,
    data_atualizacao timestamp(6) without time zone,
    data_criacao timestamp(6) without time zone,
    id bigint NOT NULL,
    material character varying(50) NOT NULL,
    nome character varying(100) NOT NULL,
    imagem_url character varying(500),
    descricao character varying(255),
    CONSTRAINT categorias_material_check CHECK (((material)::text = ANY ((ARRAY['MDF'::character varying, 'MDP'::character varying, 'MADEIRA'::character varying, 'FERRO'::character varying, 'VIDRO'::character varying, 'PLASTICO'::character varying])::text[])))
);

ALTER TABLE public.categorias ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categorias_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: fanpage_benefits; Type: TABLE; Schema: public
--

CREATE TABLE public.fanpage_benefits (
    ordem integer NOT NULL,
    fanpage_id bigint NOT NULL,
    benefit_title character varying(120),
    benefit_description character varying(255)
);

--
-- Name: fanpage_collections; Type: TABLE; Schema: public
--

CREATE TABLE public.fanpage_collections (
    ordem integer NOT NULL,
    fanpage_id bigint NOT NULL,
    collection_name character varying(120),
    collection_description character varying(255),
    collection_image_url character varying(255)
);

--
-- Name: fanpage_config; Type: TABLE; Schema: public
--

CREATE TABLE public.fanpage_config (
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    hero_primary_label character varying(100),
    hero_secondary_label character varying(100),
    combos_title character varying(160),
    cta_title character varying(160),
    hero_subtitle character varying(160),
    hero_title character varying(160),
    offers_title character varying(160),
    hero_description character varying(500),
    combos_description character varying(255),
    cta_description character varying(255),
    hero_banner_url character varying(255),
    hero_primary_message character varying(255),
    hero_secondary_url character varying(255),
    offers_description character varying(255)
);

ALTER TABLE public.fanpage_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fanpage_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: fanpage_cta_highlights; Type: TABLE; Schema: public
--

CREATE TABLE public.fanpage_cta_highlights (
    ordem integer NOT NULL,
    fanpage_id bigint NOT NULL,
    cta_highlights character varying(255)
);

--
-- Name: itens_pedido; Type: TABLE; Schema: public
--

CREATE TABLE public.itens_pedido (
    preco_unitario numeric(38,2),
    quantidade integer,
    total numeric(38,2),
    id bigint NOT NULL,
    pedido_id bigint NOT NULL,
    produto_id bigint NOT NULL
);

ALTER TABLE public.itens_pedido ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.itens_pedido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: loja_config; Type: TABLE; Schema: public
--

CREATE TABLE public.loja_config (
    cor_primaria character varying(7),
    cor_secundaria character varying(7),
    atualizado_em timestamp(6) without time zone,
    id bigint NOT NULL,
    whatsapp character varying(32),
    cta_texto character varying(80),
    nome character varying(120) NOT NULL,
    banner_url character varying(255),
    endereco character varying(255),
    logo_url character varying(255)
);

ALTER TABLE public.loja_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.loja_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: notificacao_evento; Type: TABLE; Schema: public
--

CREATE TABLE public.notificacao_evento (
    data_envio timestamp(6) with time zone,
    id bigint NOT NULL,
    assunto character varying(255),
    destinatario character varying(255),
    detalhe_erro character varying(255),
    status character varying(255),
    tipo character varying(255),
    CONSTRAINT notificacao_evento_status_check CHECK (((status)::text = ANY ((ARRAY['PENDENTE'::character varying, 'ENVIADO'::character varying, 'FALHA'::character varying])::text[]))),
    CONSTRAINT notificacao_evento_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['PEDIDO_CRIADO'::character varying, 'PAGAMENTO_APROVADO'::character varying, 'PAGAMENTO_REJEITADO'::character varying])::text[])))
);

ALTER TABLE public.notificacao_evento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notificacao_evento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: pedidos; Type: TABLE; Schema: public
--

CREATE TABLE public.pedidos (
    frete numeric(38,2),
    subtotal numeric(38,2),
    total numeric(38,2),
    atualizado_em timestamp(6) with time zone,
    criado_em timestamp(6) with time zone,
    id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    payment_id character varying(255),
    payment_method character varying(255),
    status character varying(255) NOT NULL,
    CONSTRAINT pedidos_payment_method_check CHECK (((payment_method)::text = ANY ((ARRAY['PIX'::character varying, 'CARD'::character varying, 'BOLETO'::character varying])::text[]))),
    CONSTRAINT pedidos_status_check CHECK (((status)::text = ANY ((ARRAY['CRIADO'::character varying, 'PAGO'::character varying, 'CANCELADO'::character varying, 'ENTREGUE'::character varying])::text[])))
);

ALTER TABLE public.pedidos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pedidos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: produto_diferenciais; Type: TABLE; Schema: public
--

CREATE TABLE public.produto_diferenciais (
    ordem integer NOT NULL,
    produto_id bigint NOT NULL,
    diferencial character varying(300)
);

--
-- Name: produto_imagens; Type: TABLE; Schema: public
--

CREATE TABLE public.produto_imagens (
    ordem integer NOT NULL,
    id bigint NOT NULL,
    produto_id bigint NOT NULL,
    url character varying(255) NOT NULL
);

ALTER TABLE public.produto_imagens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produto_imagens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: produto_variacoes; Type: TABLE; Schema: public
--

CREATE TABLE public.produto_variacoes (
    adicional_preco numeric(12,2),
    estoque integer,
    id bigint NOT NULL,
    produto_id bigint NOT NULL,
    sku character varying(60),
    cor character varying(80),
    tamanho character varying(80),
    imagem_url character varying(500)
);

ALTER TABLE public.produto_variacoes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produto_variacoes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: produtos; Type: TABLE; Schema: public
--

CREATE TABLE public.produtos (
    altura numeric(8,3),
    ativa boolean NOT NULL,
    estoque integer NOT NULL,
    largura numeric(8,3),
    peso numeric(8,3),
    preco numeric(12,2) NOT NULL,
    preco_original numeric(10,2),
    profundidade numeric(8,3),
    volumes integer,
    categoria_id bigint,
    data_atualizacao timestamp(6) without time zone,
    data_criacao timestamp(6) without time zone,
    id bigint NOT NULL,
    codigo character varying(30),
    sku character varying(60),
    nome character varying(150) NOT NULL,
    descricao character varying(500),
    imagem_url character varying(255)
);

ALTER TABLE public.produtos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produtos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: user_roles; Type: TABLE; Schema: public
--

CREATE TABLE public.user_roles (
    user_id bigint NOT NULL,
    role character varying(255),
    CONSTRAINT user_roles_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'CLIENTE'::character varying, 'VENDEDOR'::character varying])::text[])))
);

--
-- Name: users; Type: TABLE; Schema: public
--

CREATE TABLE public.users (
    enabled boolean NOT NULL,
    created_at timestamp(6) with time zone,
    id bigint NOT NULL,
    telefone character varying(20),
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: whatsapp_mensagem; Type: TABLE; Schema: public
--

CREATE TABLE public.whatsapp_mensagem (
    data_envio timestamp(6) with time zone,
    id bigint NOT NULL,
    notificacao_evento_id bigint,
    canal character varying(255),
    conteudo character varying(255),
    destinatario character varying(255),
    mensagem_id character varying(255),
    provedor character varying(255),
    status character varying(255),
    CONSTRAINT whatsapp_mensagem_status_check CHECK (((status)::text = ANY ((ARRAY['PENDENTE'::character varying, 'ENVIADA'::character varying, 'ENTREGUE'::character varying, 'LIDA'::character varying, 'FALHA'::character varying])::text[])))
);

ALTER TABLE public.whatsapp_mensagem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.whatsapp_mensagem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Primary keys / unique constraints
--

ALTER TABLE ONLY public.auditoria_evento ADD CONSTRAINT auditoria_evento_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.categorias ADD CONSTRAINT categorias_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.fanpage_benefits ADD CONSTRAINT fanpage_benefits_pkey PRIMARY KEY (ordem, fanpage_id);
ALTER TABLE ONLY public.fanpage_collections ADD CONSTRAINT fanpage_collections_pkey PRIMARY KEY (ordem, fanpage_id);
ALTER TABLE ONLY public.fanpage_config ADD CONSTRAINT fanpage_config_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.fanpage_cta_highlights ADD CONSTRAINT fanpage_cta_highlights_pkey PRIMARY KEY (ordem, fanpage_id);
ALTER TABLE ONLY public.itens_pedido ADD CONSTRAINT itens_pedido_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.loja_config ADD CONSTRAINT loja_config_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.notificacao_evento ADD CONSTRAINT notificacao_evento_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.pedidos ADD CONSTRAINT pedidos_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.produto_diferenciais ADD CONSTRAINT produto_diferenciais_pkey PRIMARY KEY (ordem, produto_id);
ALTER TABLE ONLY public.produto_imagens ADD CONSTRAINT produto_imagens_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.produto_variacoes ADD CONSTRAINT produto_variacoes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.produto_variacoes ADD CONSTRAINT produto_variacoes_sku_key UNIQUE (sku);
ALTER TABLE ONLY public.produtos ADD CONSTRAINT produtos_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.produtos ADD CONSTRAINT produtos_sku_key UNIQUE (sku);
ALTER TABLE ONLY public.categorias ADD CONSTRAINT uk_categoria_nome_material UNIQUE (nome, material);
ALTER TABLE ONLY public.users ADD CONSTRAINT users_email_key UNIQUE (email);
ALTER TABLE ONLY public.users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.whatsapp_mensagem ADD CONSTRAINT whatsapp_mensagem_pkey PRIMARY KEY (id);

--
-- Foreign keys
--

ALTER TABLE ONLY public.fanpage_benefits ADD CONSTRAINT fk3cf4naijs9a48fi4r3akay9ea FOREIGN KEY (fanpage_id) REFERENCES public.fanpage_config(id);
ALTER TABLE ONLY public.itens_pedido ADD CONSTRAINT fk42mycompce3b7yt3l6ukdwsxy FOREIGN KEY (pedido_id) REFERENCES public.pedidos(id);
ALTER TABLE ONLY public.whatsapp_mensagem ADD CONSTRAINT fk53qwk2x7h7in6e03c8bc2vn57 FOREIGN KEY (notificacao_evento_id) REFERENCES public.notificacao_evento(id);
ALTER TABLE ONLY public.produto_imagens ADD CONSTRAINT fk8pviicjexc5kgvrwucwe83ikt FOREIGN KEY (produto_id) REFERENCES public.produtos(id);
ALTER TABLE ONLY public.produtos ADD CONSTRAINT fk8rqw0ljwdaom34jr2t46bjtrn FOREIGN KEY (categoria_id) REFERENCES public.categorias(id);
ALTER TABLE ONLY public.produto_variacoes ADD CONSTRAINT fk96uuaijw4n1rs4xtxhw35bhsq FOREIGN KEY (produto_id) REFERENCES public.produtos(id);
ALTER TABLE ONLY public.fanpage_collections ADD CONSTRAINT fkbm8vhc5t41jjeoi4cbsgb98wg FOREIGN KEY (fanpage_id) REFERENCES public.fanpage_config(id);
ALTER TABLE ONLY public.user_roles ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.produto_diferenciais ADD CONSTRAINT fkmh7o2wnxp52kaa4dia10qbopi FOREIGN KEY (produto_id) REFERENCES public.produtos(id);
ALTER TABLE ONLY public.pedidos ADD CONSTRAINT fkpfoceigjvyas04u9bhcllnjol FOREIGN KEY (usuario_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.auditoria_evento ADD CONSTRAINT fkq0bbm9qkggkwhwkbftavrvu45 FOREIGN KEY (usuario_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.fanpage_cta_highlights ADD CONSTRAINT fkrc9u2ry5cp3gj1jt53jg8yqk0 FOREIGN KEY (fanpage_id) REFERENCES public.fanpage_config(id);
ALTER TABLE ONLY public.itens_pedido ADD CONSTRAINT fkxytdlekpdaobqphujy9bmuhl FOREIGN KEY (produto_id) REFERENCES public.produtos(id);
