-- Etapa 1 — Gestão de vendas: clientes, acesso, venda com reserva de estoque.
-- Migração ADITIVA: não altera dados de pedidos antigos além de classificá-los
-- (sem atribuir cliente/vendedor/comissão/reserva a vendas legadas).

-- ---------------------------------------------------------------------------
-- Acesso: novo perfil GERENTE e nome do usuário
-- ---------------------------------------------------------------------------
ALTER TABLE public.user_roles DROP CONSTRAINT IF EXISTS user_roles_role_check;
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_role_check
    CHECK (role IN ('ADMIN', 'GERENTE', 'CLIENTE', 'VENDEDOR'));

ALTER TABLE public.users ADD COLUMN nome character varying(120);

-- ---------------------------------------------------------------------------
-- Auditoria: novos tipos e referência à entidade afetada
-- ---------------------------------------------------------------------------
ALTER TABLE public.auditoria_evento DROP CONSTRAINT IF EXISTS auditoria_evento_tipo_check;
ALTER TABLE public.auditoria_evento ADD CONSTRAINT auditoria_evento_tipo_check CHECK (tipo IN (
    'LOGIN_SUCESSO', 'LOGIN_FALHA', 'PEDIDO_CRIADO', 'PAGAMENTO_APROVADO', 'PAGAMENTO_REJEITADO',
    'PRODUTO_CRIADO', 'PRODUTO_ATUALIZADO', 'PRODUTO_REMOVIDO', 'NOTIFICACAO_FALHA', 'NOTIFICACAO_ENVIADA',
    'USUARIO_CRIADO', 'USUARIO_ALTERADO', 'USUARIO_DESATIVADO', 'USUARIO_ATIVADO',
    'CLIENTE_CRIADO', 'CLIENTE_ALTERADO',
    'CONFIG_COMERCIAL_ALTERADA',
    'VENDA_REGISTRADA', 'VENDA_ALTERADA', 'VENDA_CONFIRMADA', 'VENDA_CANCELADA',
    'DESCONTO_SOLICITADO', 'DESCONTO_APROVADO', 'DESCONTO_REJEITADO', 'DESCONTO_INVALIDADO',
    'RESERVA_CRIADA', 'RESERVA_LIBERADA'));

ALTER TABLE public.auditoria_evento ADD COLUMN entidade character varying(40);
ALTER TABLE public.auditoria_evento ADD COLUMN entidade_id bigint;
CREATE INDEX idx_auditoria_entidade ON public.auditoria_evento (entidade, entidade_id);

-- ---------------------------------------------------------------------------
-- Catálogo: modalidade de venda (pronta entrega / encomenda)
-- ---------------------------------------------------------------------------
ALTER TABLE public.produtos ADD COLUMN modalidade character varying(20) NOT NULL DEFAULT 'PRONTA_ENTREGA';
ALTER TABLE public.produtos ADD CONSTRAINT produtos_modalidade_check
    CHECK (modalidade IN ('PRONTA_ENTREGA', 'ENCOMENDA', 'AMBAS'));
-- Prazo de encomenda (decisão D08 pendente): permanece nulo até ser definido.
ALTER TABLE public.produtos ADD COLUMN prazo_encomenda_dias integer;

-- ---------------------------------------------------------------------------
-- Clientes (pessoa física)
-- ---------------------------------------------------------------------------
CREATE TABLE public.clientes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version bigint NOT NULL DEFAULT 0,
    nome character varying(150) NOT NULL,
    cpf character varying(11),
    telefone character varying(20),
    email character varying(150),
    observacoes character varying(500),
    ativo boolean NOT NULL DEFAULT true,
    criado_em timestamp(6) with time zone NOT NULL,
    atualizado_em timestamp(6) with time zone
);
CREATE UNIQUE INDEX uk_clientes_cpf ON public.clientes (cpf) WHERE cpf IS NOT NULL;
CREATE INDEX idx_clientes_telefone ON public.clientes (telefone);
CREATE INDEX idx_clientes_nome ON public.clientes (lower(nome));

CREATE TABLE public.enderecos_cliente (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id bigint NOT NULL REFERENCES public.clientes (id),
    apelido character varying(60),
    cep character varying(8),
    logradouro character varying(150) NOT NULL,
    numero character varying(20),
    complemento character varying(100),
    bairro character varying(100),
    cidade character varying(100) NOT NULL,
    uf character varying(2) NOT NULL,
    principal boolean NOT NULL DEFAULT false
);
CREATE INDEX idx_enderecos_cliente ON public.enderecos_cliente (cliente_id);

-- ---------------------------------------------------------------------------
-- Configuração comercial (linha única, id = 1). Campos nulos = decisão pendente.
-- ---------------------------------------------------------------------------
CREATE TABLE public.configuracao_comercial (
    id bigint PRIMARY KEY,
    limite_desconto_percentual numeric(5,2),          -- D03
    arredondamento character varying(20),             -- D04
    perfis_cancelamento character varying(100),       -- D07 (lista separada por vírgula)
    atualizado_em timestamp(6) with time zone,
    atualizado_por bigint REFERENCES public.users (id),
    CONSTRAINT configuracao_comercial_arred_check
        CHECK (arredondamento IS NULL OR arredondamento IN ('HALF_UP', 'HALF_EVEN', 'DOWN', 'UP')),
    CONSTRAINT configuracao_comercial_limite_check
        CHECK (limite_desconto_percentual IS NULL OR (limite_desconto_percentual >= 0 AND limite_desconto_percentual <= 100))
);

CREATE TABLE public.condicoes_pagamento (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    forma character varying(20) NOT NULL,
    parcelas integer NOT NULL,
    ajuste_percentual numeric(7,2) NOT NULL,          -- acréscimo (+) ou desconto (-) sobre o preço base
    ativa boolean NOT NULL DEFAULT true,
    CONSTRAINT condicoes_pagamento_forma_check CHECK (forma IN ('DINHEIRO', 'PIX', 'CARTAO')),
    CONSTRAINT condicoes_pagamento_parcelas_check CHECK (parcelas >= 1),
    CONSTRAINT uk_condicao_forma_parcelas UNIQUE (forma, parcelas)
);

-- ---------------------------------------------------------------------------
-- Pedido como agregado de venda
-- ---------------------------------------------------------------------------
ALTER TABLE public.pedidos ADD COLUMN version bigint NOT NULL DEFAULT 0;
ALTER TABLE public.pedidos ADD COLUMN cliente_id bigint REFERENCES public.clientes (id);
ALTER TABLE public.pedidos ADD COLUMN vendedor_id bigint REFERENCES public.users (id);
ALTER TABLE public.pedidos ADD COLUMN canal character varying(20);
ALTER TABLE public.pedidos ADD COLUMN status_comercial character varying(30) NOT NULL DEFAULT 'LEGADO';
ALTER TABLE public.pedidos ADD COLUMN status_pagamento character varying(20) NOT NULL DEFAULT 'NAO_INFORMADO';
ALTER TABLE public.pedidos ADD COLUMN status_entrega character varying(20) NOT NULL DEFAULT 'NAO_INFORMADO';
ALTER TABLE public.pedidos ADD COLUMN status_montagem character varying(20) NOT NULL DEFAULT 'NAO_INFORMADO';
ALTER TABLE public.pedidos ADD COLUMN forma_pagamento character varying(20);
ALTER TABLE public.pedidos ADD COLUMN parcelas integer;
ALTER TABLE public.pedidos ADD COLUMN ajuste_condicao_percentual numeric(7,2);
ALTER TABLE public.pedidos ADD COLUMN tipo_entrega character varying(20);
ALTER TABLE public.pedidos ADD COLUMN entrega_cep character varying(8);
ALTER TABLE public.pedidos ADD COLUMN entrega_logradouro character varying(150);
ALTER TABLE public.pedidos ADD COLUMN entrega_numero character varying(20);
ALTER TABLE public.pedidos ADD COLUMN entrega_complemento character varying(100);
ALTER TABLE public.pedidos ADD COLUMN entrega_bairro character varying(100);
ALTER TABLE public.pedidos ADD COLUMN entrega_cidade character varying(100);
ALTER TABLE public.pedidos ADD COLUMN entrega_uf character varying(2);
ALTER TABLE public.pedidos ADD COLUMN desconto numeric(38,2) NOT NULL DEFAULT 0;
ALTER TABLE public.pedidos ADD COLUMN observacao character varying(500);
ALTER TABLE public.pedidos ADD COLUMN chave_criacao character varying(80);
ALTER TABLE public.pedidos ADD COLUMN chave_confirmacao character varying(80);
ALTER TABLE public.pedidos ADD COLUMN confirmado_em timestamp(6) with time zone;
ALTER TABLE public.pedidos ADD COLUMN cancelado_em timestamp(6) with time zone;
ALTER TABLE public.pedidos ADD COLUMN cancelado_por bigint REFERENCES public.users (id);
ALTER TABLE public.pedidos ADD COLUMN motivo_cancelamento character varying(300);
ALTER TABLE public.pedidos ADD COLUMN revisao_legado boolean NOT NULL DEFAULT false;

ALTER TABLE public.pedidos ADD CONSTRAINT pedidos_status_comercial_check CHECK (status_comercial IN
    ('LEGADO', 'RASCUNHO', 'AGUARDANDO_APROVACAO', 'CONFIRMADA', 'CANCELADA'));
ALTER TABLE public.pedidos ADD CONSTRAINT pedidos_status_pagamento_check CHECK (status_pagamento IN
    ('NAO_INFORMADO', 'PENDENTE', 'PAGO'));
ALTER TABLE public.pedidos ADD CONSTRAINT pedidos_status_entrega_check CHECK (status_entrega IN
    ('NAO_INFORMADO', 'NAO_AGENDADA', 'AGENDADA', 'SAIU', 'ENTREGUE'));
ALTER TABLE public.pedidos ADD CONSTRAINT pedidos_status_montagem_check CHECK (status_montagem IN
    ('NAO_INFORMADO', 'NAO_AGENDADA', 'AGENDADA', 'CONCLUIDA', 'NAO_NECESSARIA'));
ALTER TABLE public.pedidos ADD CONSTRAINT pedidos_canal_check CHECK (canal IS NULL OR canal IN
    ('LOJA', 'WHATSAPP', 'SITE'));
ALTER TABLE public.pedidos ADD CONSTRAINT pedidos_forma_pagamento_check CHECK (forma_pagamento IS NULL OR forma_pagamento IN
    ('DINHEIRO', 'PIX', 'CARTAO'));
ALTER TABLE public.pedidos ADD CONSTRAINT pedidos_tipo_entrega_check CHECK (tipo_entrega IS NULL OR tipo_entrega IN
    ('ENTREGA', 'RETIRADA'));

-- Mapa de conversão explícito dos pedidos antigos (sem presumir cliente, vendedor,
-- reserva, comissão ou quitação):
--   PAGO      -> pagamento quitado
--   ENTREGUE  -> entrega concluída (não presume quitação)
--   CANCELADO -> cancelada
--   CRIADO    -> exige revisão
UPDATE public.pedidos SET status_pagamento = 'PAGO'     WHERE status = 'PAGO';
UPDATE public.pedidos SET status_entrega   = 'ENTREGUE' WHERE status = 'ENTREGUE';
UPDATE public.pedidos SET status_comercial = 'CANCELADA' WHERE status = 'CANCELADO';
UPDATE public.pedidos SET revisao_legado = true WHERE status = 'CRIADO';

CREATE UNIQUE INDEX uk_pedidos_chave_criacao ON public.pedidos (chave_criacao) WHERE chave_criacao IS NOT NULL;
CREATE INDEX idx_pedidos_cliente ON public.pedidos (cliente_id);
CREATE INDEX idx_pedidos_vendedor ON public.pedidos (vendedor_id);
CREATE INDEX idx_pedidos_status_comercial ON public.pedidos (status_comercial);
CREATE INDEX idx_pedidos_payment_id ON public.pedidos (payment_id);

-- ---------------------------------------------------------------------------
-- Itens: variação, histórico de SKU/descrição, preço base, modalidade e custo
-- ---------------------------------------------------------------------------
ALTER TABLE public.itens_pedido ADD COLUMN variacao_id bigint REFERENCES public.produto_variacoes (id);
ALTER TABLE public.itens_pedido ADD COLUMN sku_historico character varying(60);
ALTER TABLE public.itens_pedido ADD COLUMN descricao_historica character varying(300);
ALTER TABLE public.itens_pedido ADD COLUMN preco_base numeric(38,2);
ALTER TABLE public.itens_pedido ADD COLUMN modalidade character varying(20);
ALTER TABLE public.itens_pedido ADD COLUMN custo_unitario numeric(38,2);
ALTER TABLE public.itens_pedido ADD CONSTRAINT itens_pedido_modalidade_check
    CHECK (modalidade IS NULL OR modalidade IN ('PRONTA_ENTREGA', 'ENCOMENDA'));
CREATE INDEX idx_itens_pedido_pedido ON public.itens_pedido (pedido_id);
CREATE INDEX idx_itens_pedido_produto ON public.itens_pedido (produto_id);
CREATE INDEX idx_itens_pedido_variacao ON public.itens_pedido (variacao_id);

-- ---------------------------------------------------------------------------
-- Desconto: solicitações e aprovações
-- ---------------------------------------------------------------------------
CREATE TABLE public.solicitacoes_desconto (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id bigint NOT NULL REFERENCES public.pedidos (id),
    solicitante_id bigint NOT NULL REFERENCES public.users (id),
    valor_desconto numeric(38,2) NOT NULL,
    percentual numeric(9,4) NOT NULL,
    subtotal_base numeric(38,2) NOT NULL,
    status character varying(20) NOT NULL,
    justificativa character varying(300),
    decidido_por bigint REFERENCES public.users (id),
    decidido_em timestamp(6) with time zone,
    motivo_decisao character varying(300),
    criado_em timestamp(6) with time zone NOT NULL,
    CONSTRAINT solicitacoes_desconto_status_check CHECK (status IN ('PENDENTE', 'APROVADA', 'REJEITADA', 'INVALIDADA'))
);
CREATE INDEX idx_solicitacoes_desconto_pedido ON public.solicitacoes_desconto (pedido_id);
CREATE INDEX idx_solicitacoes_desconto_status ON public.solicitacoes_desconto (status);

-- ---------------------------------------------------------------------------
-- Reserva de estoque (criada na confirmação da venda)
-- ---------------------------------------------------------------------------
CREATE TABLE public.reservas_estoque (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id bigint NOT NULL REFERENCES public.pedidos (id),
    item_id bigint NOT NULL REFERENCES public.itens_pedido (id),
    produto_id bigint NOT NULL REFERENCES public.produtos (id),
    variacao_id bigint REFERENCES public.produto_variacoes (id),
    quantidade integer NOT NULL,
    status character varying(20) NOT NULL,
    criada_em timestamp(6) with time zone NOT NULL,
    liberada_em timestamp(6) with time zone,
    motivo_liberacao character varying(300),
    CONSTRAINT reservas_estoque_status_check CHECK (status IN ('ATIVA', 'LIBERADA', 'CONSUMIDA')),
    CONSTRAINT reservas_estoque_quantidade_check CHECK (quantidade > 0)
);
CREATE INDEX idx_reservas_pedido ON public.reservas_estoque (pedido_id);
CREATE INDEX idx_reservas_produto_status ON public.reservas_estoque (produto_id, status);
CREATE INDEX idx_reservas_variacao_status ON public.reservas_estoque (variacao_id, status);
-- No máximo uma reserva ativa por item (a confirmação não pode duplicar reservas).
CREATE UNIQUE INDEX uk_reserva_ativa_item ON public.reservas_estoque (item_id) WHERE status = 'ATIVA';
