-- Etapa 2 — Atendimento e pós-venda: encomendas, movimentações e inventário, saída com baixa,
-- entrega, montagem e pós-venda. Migração ADITIVA (não altera V1–V3).

-- ---------------------------------------------------------------------------
-- Pedido: saída (baixa física) e novo estado de entrega
-- ---------------------------------------------------------------------------
ALTER TABLE public.pedidos ADD COLUMN saida_realizada_em timestamp(6) with time zone;
ALTER TABLE public.pedidos ADD COLUMN chave_saida character varying(80);

ALTER TABLE public.pedidos DROP CONSTRAINT IF EXISTS pedidos_status_entrega_check;
ALTER TABLE public.pedidos ADD CONSTRAINT pedidos_status_entrega_check CHECK (status_entrega IN
    ('NAO_INFORMADO', 'NAO_AGENDADA', 'AGENDADA', 'SAIU', 'TENTATIVA_FRUSTRADA', 'ENTREGUE'));

-- ---------------------------------------------------------------------------
-- Configuração comercial: D05 (pagamento exigido para expedir). Nulo = pendente.
-- ---------------------------------------------------------------------------
ALTER TABLE public.configuracao_comercial ADD COLUMN exige_pagamento_expedir boolean;

-- ---------------------------------------------------------------------------
-- Auditoria: novos tipos (conjunto anterior + Etapa 2)
-- ---------------------------------------------------------------------------
ALTER TABLE public.auditoria_evento DROP CONSTRAINT IF EXISTS auditoria_evento_tipo_check;
ALTER TABLE public.auditoria_evento ADD CONSTRAINT auditoria_evento_tipo_check CHECK (tipo IN (
    'LOGIN_SUCESSO', 'LOGIN_FALHA', 'PEDIDO_CRIADO', 'PAGAMENTO_APROVADO', 'PAGAMENTO_REJEITADO',
    'PRODUTO_CRIADO', 'PRODUTO_ATUALIZADO', 'PRODUTO_REMOVIDO', 'NOTIFICACAO_FALHA', 'NOTIFICACAO_ENVIADA',
    'USUARIO_CRIADO', 'USUARIO_ALTERADO', 'USUARIO_DESATIVADO', 'USUARIO_ATIVADO',
    'CLIENTE_CRIADO', 'CLIENTE_ALTERADO',
    'CONFIG_COMERCIAL_ALTERADA',
    'VENDA_REGISTRADA', 'VENDA_ALTERADA', 'VENDA_CONFIRMADA', 'VENDA_CANCELADA',
    'DESCONTO_SOLICITADO', 'DESCONTO_APROVADO', 'DESCONTO_REJEITADO', 'DESCONTO_INVALIDADO',
    'RESERVA_CRIADA', 'RESERVA_LIBERADA',
    'ENCOMENDA_ATUALIZADA', 'ENCOMENDA_RECEBIDA', 'ESTOQUE_AJUSTADO', 'SAIDA_REGISTRADA',
    'ENTREGA_AGENDADA', 'ENTREGA_REAGENDADA', 'ENTREGA_FRUSTRADA', 'ENTREGA_CONCLUIDA',
    'MONTAGEM_AGENDADA', 'MONTAGEM_CONCLUIDA', 'MONTAGEM_DISPENSADA',
    'OCORRENCIA_ABERTA', 'OCORRENCIA_ATUALIZADA', 'DEVOLUCAO_RECEBIDA', 'OCORRENCIA_RESOLVIDA',
    'OCORRENCIA_CANCELADA'));

-- ---------------------------------------------------------------------------
-- Encomendas: acompanhamento (a compra é feita fora do sistema)
-- ---------------------------------------------------------------------------
CREATE TABLE public.encomendas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version bigint NOT NULL DEFAULT 0,
    pedido_id bigint NOT NULL REFERENCES public.pedidos (id),
    item_id bigint NOT NULL REFERENCES public.itens_pedido (id),
    status character varying(30) NOT NULL,
    fornecedor character varying(150),
    referencia_fornecedor character varying(100),
    previsao_chegada date,
    observacao character varying(300),
    quantidade_recebida integer,
    recebida_em timestamp(6) with time zone,
    recebida_por bigint REFERENCES public.users (id),
    chave_recebimento character varying(80),
    criada_em timestamp(6) with time zone NOT NULL,
    CONSTRAINT encomendas_status_check CHECK (status IN ('AGUARDANDO_PEDIDO', 'PEDIDO_REALIZADO', 'RECEBIDA', 'CANCELADA')),
    CONSTRAINT uk_encomenda_item UNIQUE (item_id)
);
CREATE INDEX idx_encomendas_pedido ON public.encomendas (pedido_id);
CREATE INDEX idx_encomendas_status ON public.encomendas (status);

-- ---------------------------------------------------------------------------
-- Entrega (uma por pedido: sem entrega parcial) e seu histórico
-- ---------------------------------------------------------------------------
CREATE TABLE public.entregas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version bigint NOT NULL DEFAULT 0,
    pedido_id bigint NOT NULL REFERENCES public.pedidos (id),
    tipo character varying(20) NOT NULL,
    status character varying(30) NOT NULL,
    data_prevista date NOT NULL,
    periodo character varying(20) NOT NULL,
    equipe character varying(150),
    observacao character varying(300),
    criada_em timestamp(6) with time zone NOT NULL,
    criada_por bigint REFERENCES public.users (id),
    saida_em timestamp(6) with time zone,
    concluida_em timestamp(6) with time zone,
    recebedor_nome character varying(150),
    comprovante_arquivo character varying(300),
    observacao_conclusao character varying(300),
    CONSTRAINT entregas_tipo_check CHECK (tipo IN ('ENTREGA', 'RETIRADA')),
    CONSTRAINT entregas_status_check CHECK (status IN ('AGENDADA', 'SAIU', 'TENTATIVA_FRUSTRADA', 'ENTREGUE', 'CANCELADA')),
    CONSTRAINT entregas_periodo_check CHECK (periodo IN ('MANHA', 'TARDE', 'DIA_INTEIRO')),
    CONSTRAINT uk_entrega_pedido UNIQUE (pedido_id)
);
CREATE INDEX idx_entregas_data ON public.entregas (data_prevista);

CREATE TABLE public.entrega_eventos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entrega_id bigint NOT NULL REFERENCES public.entregas (id),
    tipo character varying(30) NOT NULL,
    data_prevista date,
    periodo character varying(20),
    equipe character varying(150),
    motivo character varying(300),
    arquivo character varying(300),
    usuario_id bigint REFERENCES public.users (id),
    criado_em timestamp(6) with time zone NOT NULL,
    CONSTRAINT entrega_eventos_tipo_check CHECK (tipo IN
        ('AGENDADA', 'REAGENDADA', 'SAIDA', 'TENTATIVA_FRUSTRADA', 'ENTREGUE', 'CANCELADA'))
);
CREATE INDEX idx_entrega_eventos_entrega ON public.entrega_eventos (entrega_id);

-- ---------------------------------------------------------------------------
-- Montagem (inclusa; sem cobrança adicional)
-- ---------------------------------------------------------------------------
CREATE TABLE public.montagens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version bigint NOT NULL DEFAULT 0,
    pedido_id bigint NOT NULL REFERENCES public.pedidos (id),
    status character varying(30) NOT NULL,
    data_prevista date,
    periodo character varying(20),
    responsavel character varying(150),
    observacao character varying(300),
    concluida_em timestamp(6) with time zone,
    evidencia_arquivo character varying(300),
    motivo_dispensa character varying(300),
    criada_em timestamp(6) with time zone NOT NULL,
    atualizada_por bigint REFERENCES public.users (id),
    CONSTRAINT montagens_status_check CHECK (status IN ('AGENDADA', 'CONCLUIDA', 'NAO_NECESSARIA')),
    CONSTRAINT montagens_periodo_check CHECK (periodo IS NULL OR periodo IN ('MANHA', 'TARDE', 'DIA_INTEIRO')),
    CONSTRAINT uk_montagem_pedido UNIQUE (pedido_id)
);
CREATE INDEX idx_montagens_data ON public.montagens (data_prevista);

-- ---------------------------------------------------------------------------
-- Pós-venda: assistência, troca e devolução
-- ---------------------------------------------------------------------------
CREATE TABLE public.ocorrencias_pos_venda (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version bigint NOT NULL DEFAULT 0,
    pedido_id bigint NOT NULL REFERENCES public.pedidos (id),
    item_id bigint REFERENCES public.itens_pedido (id),
    tipo character varying(20) NOT NULL,
    status character varying(30) NOT NULL,
    descricao character varying(500) NOT NULL,
    quantidade integer,
    troca_produto_id bigint REFERENCES public.produtos (id),
    troca_variacao_id bigint REFERENCES public.produto_variacoes (id),
    troca_quantidade integer,
    diferenca_calculada numeric(38,2),
    condicao_fisica character varying(20),
    avaliacao character varying(300),
    devolucao_recebida_em timestamp(6) with time zone,
    devolucao_recebida_por bigint REFERENCES public.users (id),
    estoque_reposto boolean NOT NULL DEFAULT false,
    chave_devolucao character varying(80),
    solucao character varying(500),
    resolvida_em timestamp(6) with time zone,
    resolvida_por bigint REFERENCES public.users (id),
    motivo_cancelamento character varying(300),
    aberta_por bigint NOT NULL REFERENCES public.users (id),
    criada_em timestamp(6) with time zone NOT NULL,
    CONSTRAINT ocorrencias_tipo_check CHECK (tipo IN ('ASSISTENCIA', 'TROCA', 'DEVOLUCAO')),
    CONSTRAINT ocorrencias_status_check CHECK (status IN ('ABERTA', 'DEVOLUCAO_RECEBIDA', 'RESOLVIDA', 'CANCELADA')),
    CONSTRAINT ocorrencias_condicao_check CHECK (condicao_fisica IS NULL OR condicao_fisica IN ('APTA_REVENDA', 'NAO_APTA'))
);
CREATE INDEX idx_ocorrencias_pedido ON public.ocorrencias_pos_venda (pedido_id);
CREATE INDEX idx_ocorrencias_status ON public.ocorrencias_pos_venda (status);

CREATE TABLE public.ocorrencia_evidencias (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ocorrencia_id bigint NOT NULL REFERENCES public.ocorrencias_pos_venda (id),
    arquivo character varying(300) NOT NULL,
    descricao character varying(200),
    enviado_por bigint REFERENCES public.users (id),
    criado_em timestamp(6) with time zone NOT NULL
);
CREATE INDEX idx_ocorrencia_evidencias ON public.ocorrencia_evidencias (ocorrencia_id);

-- ---------------------------------------------------------------------------
-- Movimentações de estoque (trilha do saldo físico)
-- ---------------------------------------------------------------------------
CREATE TABLE public.movimentacoes_estoque (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo character varying(30) NOT NULL,
    produto_id bigint NOT NULL REFERENCES public.produtos (id),
    variacao_id bigint REFERENCES public.produto_variacoes (id),
    quantidade integer NOT NULL,                      -- variação do saldo (+ entrada, - saída); 0 só na 1ª contagem de saldo nulo
    saldo_anterior integer,
    saldo_posterior integer NOT NULL,
    pedido_id bigint REFERENCES public.pedidos (id),
    item_id bigint REFERENCES public.itens_pedido (id),
    encomenda_id bigint REFERENCES public.encomendas (id),
    ocorrencia_id bigint REFERENCES public.ocorrencias_pos_venda (id),
    motivo character varying(300),
    usuario_id bigint REFERENCES public.users (id),
    chave character varying(80),
    criado_em timestamp(6) with time zone NOT NULL,
    CONSTRAINT movimentacoes_tipo_check CHECK (tipo IN
        ('ENTRADA_ENCOMENDA', 'SAIDA_VENDA', 'AJUSTE_INVENTARIO', 'ENTRADA_DEVOLUCAO')),
    CONSTRAINT movimentacoes_saldo_check CHECK (saldo_posterior >= 0)
);
CREATE INDEX idx_movimentacoes_produto ON public.movimentacoes_estoque (produto_id, variacao_id, criado_em);
CREATE INDEX idx_movimentacoes_pedido ON public.movimentacoes_estoque (pedido_id);
CREATE UNIQUE INDEX uk_movimentacoes_chave ON public.movimentacoes_estoque (chave) WHERE chave IS NOT NULL;
-- A baixa de um item por saída só pode acontecer uma vez.
CREATE UNIQUE INDEX uk_movimentacao_saida_item ON public.movimentacoes_estoque (item_id) WHERE tipo = 'SAIDA_VENDA';
